DB_USERNAME: postgres
DB_PASSWORD: postgres
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: chillers
DDL_AUTO_MODE: create-drop
SQL_INIT_MODE: always
# actuator #
management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
#      base-path: /brad
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always