spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  sql:
    init:
      mode: ${SQL_INIT_MODE}
      continue-on-error: false
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.POSTGRESQLDialect
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_MODE}
    generate-ddl: false
