spring:

  banner:
    location: classpath:/banner/banner.txt
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  sql:
    init:
      mode: ${SQL_INIT_MODE}
      continue-on-error: false
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
  profiles:
    active: ${ACTIVE_PROFILE}

  # actuator
management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
application:
  title: @project.artifactId@
  version: @project.version@