### create a game
POST localhost:8080/games/new
Content-Type: application/json

{
  "team1": [
    {
      "id": 5
    },
    {
      "id": 2
    },
    {
      "id": 6
    }
  ],
  "team2": [
    {
      "id": 1
    },
    {
      "id": 4
    },
    {
      "id": 3
    }
  ],
  "gameFormat": "FORMAT_2V2"
}

### save a game
PATCH http://localhost:8080/games/save
Content-Type: application/json

{
  "id": 3,
  "outcome": "TEAM2_WINS",
  "mvp": {
    "id": 1
  }
}

### GAMES: get 1
GET localhost:8080/games/1

### GAMES: get ALL
GET localhost:8080/games/all

### PLAYERS: get ALL
GET localhost:8080/players/all

### PLAYERS: create
POST localhost:8080/players
Content-Type: application/json

{
  "nickname": "Geronimo"
}

